import type { FlowDefinition } from './types';

export const adminLifecycle: FlowDefinition = {
  id: 'admin-lifecycle',
  label: 'RAV Admin Operations',
  description: 'Administrative workflows for the RAV team: approvals, verifications, escrow management, and issue resolution.',
  primaryRole: 'rav_admin',
  roleEmoji: '🛡️',
  direction: 'TD',
  steps: [
    {
      id: 'dashboard',
      route: '/admin',
      label: 'Admin Dashboard',
      component: 'AdminOverview',
      nodeStyle: 'start',
      roles: ['rav_owner', 'rav_admin', 'rav_staff'],
      description: 'KPI overview, charts, pending action counts',
      tables: ['bookings', 'listings', 'profiles'],
    },
    {
      id: 'user_approvals',
      route: '/admin',
      label: 'User Approvals',
      component: 'PendingApprovals',
      tab: 'users',
      roles: ['rav_admin'],
      description: 'Approve or reject new user registrations',
      tables: ['profiles'],
      edgeFunctions: ['send-approval-email'],
      branches: [
        { condition: 'Approve', targetStepId: 'role_management', label: 'Approved' },
        { condition: 'Reject', targetStepId: 'dashboard', label: 'Rejected', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'role_management',
      route: '/admin',
      label: 'Role Upgrades',
      component: 'RoleUpgradeRequests',
      tab: 'users',
      roles: ['rav_owner', 'rav_admin'],
      description: 'Process role upgrade requests (renter → property_owner)',
      tables: ['role_upgrade_requests', 'user_roles'],
    },
    {
      id: 'listing_approval',
      route: '/admin',
      label: 'Listing Approval',
      component: 'AdminListings',
      tab: 'listings',
      roles: ['rav_admin', 'rav_staff'],
      nodeStyle: 'decision',
      description: 'Review and approve/reject property listings',
      tables: ['listings', 'properties'],
      branches: [
        { condition: 'Approve', targetStepId: 'verification_review', label: 'Approved' },
        { condition: 'Reject', targetStepId: 'listing_approval', label: 'Rejected', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'verification_review',
      route: '/admin',
      label: 'Verify Owner Docs',
      component: 'AdminVerifications',
      tab: 'verifications',
      roles: ['rav_admin'],
      description: 'Review owner verification documents, update trust level',
      tables: ['owner_verifications', 'verification_documents'],
    },
    {
      id: 'booking_oversight',
      route: '/admin',
      label: 'Booking Oversight',
      component: 'AdminBookings',
      tab: 'bookings',
      roles: ['rav_admin', 'rav_staff'],
      description: 'Monitor all bookings across the platform',
      tables: ['bookings', 'booking_confirmations'],
    },
    {
      id: 'escrow_management',
      route: '/admin',
      label: 'Escrow Management',
      component: 'AdminEscrow',
      tab: 'escrow',
      roles: ['rav_admin'],
      nodeStyle: 'decision',
      description: 'Verify resort confirmations, manage escrow releases',
      tables: ['booking_confirmations'],
      branches: [
        { condition: 'Verified', targetStepId: 'payout_tracking', label: 'Release' },
        { condition: 'Issue found', targetStepId: 'issue_resolution', label: 'Hold', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'payout_tracking',
      route: '/admin',
      label: 'Payout Tracking',
      component: 'AdminPayouts',
      tab: 'payouts',
      roles: ['rav_admin'],
      description: 'Track and process owner payouts',
      tables: ['bookings'],
    },
    {
      id: 'issue_resolution',
      route: '/admin',
      label: 'Issue Resolution',
      component: 'AdminCheckinIssues',
      tab: 'issues',
      roles: ['rav_admin', 'rav_staff'],
      description: 'Resolve renter check-in complaints and disputes',
      tables: ['checkin_confirmations'],
    },
    {
      id: 'financials',
      route: '/admin',
      label: 'Financial Reports',
      component: 'AdminFinancials',
      tab: 'financials',
      roles: ['rav_owner', 'rav_admin'],
      description: 'Revenue reports, commission tracking, marketplace analytics',
      tables: ['bookings', 'listings'],
    },
    {
      id: 'voice_controls',
      route: '/admin',
      label: 'Voice Controls',
      component: 'VoiceControls',
      tab: 'voice',
      roles: ['rav_owner', 'rav_admin'],
      description: 'Voice search admin controls: tier quotas, per-user overrides, usage dashboard, observability logs, and alert thresholds',
      tables: ['voice_search_logs', 'voice_user_overrides', 'voice_search_usage', 'membership_tiers', 'system_settings'],
    },
    {
      id: 'executive_dashboard',
      route: '/executive-dashboard',
      label: 'Executive Dashboard',
      component: 'ExecutiveDashboard',
      roles: ['rav_owner', 'rav_admin'],
      nodeStyle: 'end',
      description: 'Strategic business intelligence: GMV, Liquidity Score, market benchmarks, unit economics',
      tables: ['bookings', 'listings', 'listing_bids', 'voice_search_usage', 'system_settings'],
      edgeFunctions: ['fetch-industry-news', 'fetch-macro-indicators', 'fetch-airdna-data', 'fetch-str-data'],
    },
  ],
};
