import type { FlowDefinition } from './types';

export const adminLifecycle: FlowDefinition = {
  id: 'admin-lifecycle',
  label: 'RAV Admin Operations',
  description: 'Administrative workflows for the RAV team: approvals, verifications, escrow management, and issue resolution. The Admin Dashboard is the central hub with independent operational tracks.',
  primaryRole: 'rav_admin',
  roleEmoji: '🛡️',
  direction: 'TD',
  steps: [
    {
      id: 'dashboard',
      route: '/admin',
      label: 'Admin Dashboard',
      component: 'AdminOverview',
      nodeStyle: 'start',
      roles: ['rav_owner', 'rav_admin', 'rav_staff'],
      description: 'KPI overview, charts, pending action counts. Central hub for all admin operations.',
      tables: ['bookings', 'listings', 'profiles'],
      branches: [
        { condition: 'User management', targetStepId: 'user_approvals', label: 'Users' },
        { condition: 'Content review', targetStepId: 'listing_approval', label: 'Listings' },
        { condition: 'Booking operations', targetStepId: 'booking_oversight', label: 'Bookings' },
        { condition: 'Support queue', targetStepId: 'issue_resolution', label: 'Issues' },
        { condition: 'Analytics & reports', targetStepId: 'financials', label: 'Reports' },
      ],
    },

    // ── Track 1: User Onboarding ──
    {
      id: 'user_approvals',
      route: '/admin',
      label: 'User Approvals',
      component: 'PendingApprovals',
      tab: 'users',
      roles: ['rav_admin'],
      description: 'Approve or reject new user registrations',
      tables: ['profiles'],
      edgeFunctions: ['send-approval-email', 'send-email'],
      branches: [
        { condition: 'Approved, may request owner role', targetStepId: 'role_management', label: 'Approved' },
        { condition: 'Rejected', targetStepId: 'dashboard', label: 'Back to queue', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'role_management',
      route: '/admin',
      label: 'Role Upgrades',
      component: 'RoleUpgradeRequests',
      tab: 'users',
      roles: ['rav_owner', 'rav_admin'],
      description: 'Process role upgrade requests (renter → property_owner)',
      tables: ['role_upgrade_requests', 'user_roles'],
      branches: [
        { condition: 'Owner needs verification', targetStepId: 'verification_review', label: 'Verify docs' },
      ],
    },

    // ── Track 2: Content Review ──
    {
      id: 'listing_approval',
      route: '/admin',
      label: 'Listing Approval',
      component: 'AdminListings',
      tab: 'listings',
      roles: ['rav_admin', 'rav_staff'],
      nodeStyle: 'decision',
      description: 'Review and approve/reject property listings',
      tables: ['listings', 'properties'],
      branches: [
        { condition: 'Approved', targetStepId: 'verification_review', label: 'Approved' },
        { condition: 'Rejected, sent back to owner', targetStepId: 'dashboard', label: 'Rejected → owner fixes', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'verification_review',
      route: '/admin',
      label: 'Verify Owner Docs',
      component: 'AdminVerifications',
      tab: 'verifications',
      roles: ['rav_admin'],
      description: 'Review owner verification documents, update trust level',
      tables: ['owner_verifications', 'verification_documents'],
      branches: [],
    },

    // ── Track 3: Booking Operations ──
    {
      id: 'booking_oversight',
      route: '/admin',
      label: 'Booking Oversight',
      component: 'AdminBookings',
      tab: 'bookings',
      roles: ['rav_admin', 'rav_staff'],
      description: 'Monitor all bookings across the platform',
      tables: ['bookings', 'booking_confirmations'],
      branches: [
        { condition: 'Booking needs escrow review', targetStepId: 'escrow_management', label: 'Escrow' },
      ],
    },
    {
      id: 'escrow_management',
      route: '/admin',
      label: 'Escrow Management',
      component: 'AdminEscrow',
      tab: 'escrow',
      roles: ['rav_admin'],
      nodeStyle: 'decision',
      description: 'Verify resort confirmations, manage escrow releases, auto-release after hold period',
      tables: ['booking_confirmations'],
      edgeFunctions: ['process-escrow-release'],
      branches: [
        { condition: 'Verified + hold period elapsed', targetStepId: 'payout_tracking', label: 'Release funds' },
        { condition: 'Admin manual release', targetStepId: 'payout_tracking', label: 'Manual release' },
        { condition: 'Issue found during verification', targetStepId: 'issue_resolution', label: 'Hold → investigate', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'payout_tracking',
      route: '/admin',
      label: 'Payout Tracking',
      component: 'AdminPayouts',
      tab: 'payouts',
      roles: ['rav_admin'],
      description: 'Track and process owner payouts via Stripe Connect or manual methods',
      tables: ['bookings'],
      edgeFunctions: ['create-stripe-payout'],
      branches: [],
    },

    // ── Track 4: Support & Disputes ──
    {
      id: 'issue_resolution',
      route: '/admin',
      label: 'Issue Resolution',
      component: 'AdminCheckinIssues',
      tab: 'issues',
      roles: ['rav_admin', 'rav_staff'],
      description: 'Resolve renter check-in complaints and reported issues',
      tables: ['checkin_confirmations', 'disputes'],
      branches: [
        { condition: 'Escalated to formal dispute', targetStepId: 'dispute_resolution', label: 'Escalate' },
        { condition: 'Resolved directly', targetStepId: 'dashboard', label: 'Resolved', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'dispute_resolution',
      route: '/admin',
      label: 'Dispute Resolution',
      component: 'AdminDisputes',
      tab: 'disputes',
      roles: ['rav_admin', 'rav_staff'],
      nodeStyle: 'decision',
      description: 'Manage renter/owner disputes: investigate, communicate, issue refunds',
      tables: ['disputes', 'dispute_messages', 'bookings'],
      edgeFunctions: ['process-dispute-refund'],
      branches: [
        { condition: 'Full or partial refund', targetStepId: 'payout_tracking', label: 'Process refund' },
        { condition: 'No refund, dispute closed', targetStepId: 'financials', label: 'Closed → log', edgeStyle: 'dashed' },
      ],
    },

    // ── Track 5: Analytics & Configuration ──
    {
      id: 'financials',
      route: '/admin',
      label: 'Financial Reports',
      component: 'AdminFinancials',
      tab: 'financials',
      roles: ['rav_owner', 'rav_admin'],
      description: 'Revenue reports, commission tracking, marketplace analytics',
      tables: ['bookings', 'listings'],
      branches: [
        { condition: 'Deep-dive analytics', targetStepId: 'executive_dashboard', label: 'Executive view' },
      ],
    },
    {
      id: 'voice_controls',
      route: '/admin',
      label: 'Voice Controls',
      component: 'VoiceControls',
      tab: 'voice',
      roles: ['rav_owner', 'rav_admin'],
      description: 'Voice search admin controls: tier quotas, per-user overrides, usage dashboard, observability logs, and alert thresholds',
      tables: ['voice_search_logs', 'voice_user_overrides', 'voice_search_usage', 'membership_tiers', 'system_settings'],
      branches: [],
    },
    {
      id: 'executive_dashboard',
      route: '/executive-dashboard',
      label: 'Executive Dashboard',
      component: 'ExecutiveDashboard',
      roles: ['rav_owner', 'rav_admin'],
      nodeStyle: 'end',
      description: 'Strategic business intelligence: GMV, Liquidity Score, market benchmarks, unit economics',
      tables: ['bookings', 'listings', 'listing_bids', 'voice_search_usage', 'system_settings'],
      edgeFunctions: ['fetch-industry-news', 'fetch-macro-indicators', 'fetch-airdna-data', 'fetch-str-data'],
    },
  ],
};
