import type { FlowDefinition } from './types';

export const ownerLifecycle: FlowDefinition = {
  id: 'owner-lifecycle',
  label: 'Property Owner Journey',
  description: 'End-to-end lifecycle from signup to payout for property owners listing their timeshare weeks.',
  primaryRole: 'property_owner',
  roleEmoji: '✓',
  direction: 'TD',
  steps: [
    {
      id: 'signup',
      route: '/signup',
      label: 'Sign Up',
      component: 'Signup',
      nodeStyle: 'start',
      description: 'Owner registers with email/password or Google OAuth',
      tables: ['profiles', 'user_roles'],
    },
    {
      id: 'pending_approval',
      route: '/pending-approval',
      label: 'Await Approval',
      component: 'PendingApproval',
      nodeStyle: 'decision',
      description: 'Account pending RAV team review',
      tables: ['profiles'],
      branches: [
        { condition: 'Approved', targetStepId: 'request_owner_role', label: 'Approved' },
        { condition: 'Rejected', targetStepId: 'signup', label: 'Rejected', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'request_owner_role',
      route: '/owner-dashboard',
      label: 'Request Owner Role',
      component: 'RoleUpgradeDialog',
      description: 'User requests property_owner role upgrade',
      tables: ['role_upgrade_requests'],
    },
    {
      id: 'verify_identity',
      route: '/owner-dashboard',
      label: 'Upload Verification',
      component: 'OwnerVerification',
      tab: 'verification',
      description: 'Owner uploads deed, certificate, or ID documents',
      tables: ['owner_verifications', 'verification_documents'],
      edgeFunctions: ['send-verification-notification'],
    },
    {
      id: 'create_property',
      route: '/list-property',
      label: 'Create Property',
      component: 'ListProperty',
      roles: ['property_owner'],
      description: 'Define vacation club unit details, amenities, images',
      tables: ['properties'],
    },
    {
      id: 'create_listing',
      route: '/owner-dashboard',
      label: 'Create Listing',
      component: 'OwnerListings',
      tab: 'listings',
      roles: ['property_owner'],
      description: 'Set available dates, nightly rate pricing, cancellation policy',
      tables: ['listings'],
    },
    {
      id: 'admin_review',
      route: '/admin',
      label: 'Admin Reviews Listing',
      component: 'AdminListings',
      roles: ['rav_admin', 'rav_staff'],
      nodeStyle: 'decision',
      description: 'RAV team approves or rejects the listing',
      tables: ['listings'],
      branches: [
        { condition: 'Approved', targetStepId: 'listing_active', label: 'Approved' },
        { condition: 'Rejected', targetStepId: 'create_listing', label: 'Needs changes', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'listing_active',
      route: '/rentals',
      label: 'Listing Live',
      component: 'Rentals',
      description: 'Listing visible to renters on the marketplace. Auto-matches open travel requests.',
      tables: ['listings', 'notifications'],
      edgeFunctions: ['match-travel-requests'],
      branches: [
        { condition: 'Direct booking', targetStepId: 'booking_confirmed' },
        { condition: 'Open for bidding', targetStepId: 'manage_bids' },
      ],
    },
    {
      id: 'manage_bids',
      route: '/owner-dashboard',
      label: 'Manage Bids & Date Proposals',
      component: 'OwnerDashboard',
      tab: 'proposals',
      description: 'Owner reviews and responds to renter bids and date proposals',
      tables: ['listing_bids'],
      branches: [
        { condition: 'Bid accepted', targetStepId: 'booking_confirmed' },
        { condition: 'Counter-offered', targetStepId: 'manage_bids', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'booking_confirmed',
      route: '/owner-dashboard',
      label: 'Booking Confirmed',
      component: 'OwnerBookings',
      tab: 'bookings',
      description: 'Renter payment captured, booking created',
      tables: ['bookings', 'booking_confirmations'],
      edgeFunctions: ['verify-booking-payment'],
    },
    {
      id: 'owner_confirmation',
      route: '/owner-dashboard',
      label: 'Owner Confirmation',
      component: 'OwnerConfirmationTimer',
      tab: 'confirmations',
      roles: ['property_owner'],
      nodeStyle: 'decision',
      description: 'Owner confirms they can fulfill the booking within configurable time window. Can request time extensions.',
      tables: ['booking_confirmations'],
      branches: [
        { condition: 'Owner confirms', targetStepId: 'submit_confirmation', label: 'Confirmed' },
        { condition: 'Owner declines or times out', targetStepId: 'booking_confirmed', label: 'Cancelled', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'submit_confirmation',
      route: '/owner-dashboard',
      label: 'Submit Resort Confirmation',
      component: 'OwnerBookingConfirmations',
      tab: 'bookings',
      description: 'Owner provides resort confirmation number before deadline',
      tables: ['booking_confirmations'],
      edgeFunctions: ['send-booking-confirmation-reminder'],
    },
    {
      id: 'escrow_verified',
      route: '/admin',
      label: 'Escrow Verified',
      component: 'AdminEscrow',
      roles: ['rav_admin'],
      description: 'RAV verifies resort confirmation, releases escrow',
      tables: ['booking_confirmations'],
    },
    {
      id: 'payout',
      route: '/owner-dashboard',
      label: 'Payout Received',
      component: 'OwnerEarnings',
      tab: 'earnings',
      nodeStyle: 'end',
      description: 'Owner receives payout after checkout + 5 days',
      tables: ['bookings'],
    },
  ],
};
