import type { FlowDefinition } from './types';

export const travelerLifecycle: FlowDefinition = {
  id: 'traveler-lifecycle',
  label: 'Traveler Journey',
  description: 'End-to-end lifecycle from browsing to check-in for travelers booking vacation rentals.',
  primaryRole: 'renter',
  roleEmoji: '🧳',
  direction: 'TD',
  steps: [
    {
      id: 'browse',
      route: '/',
      label: 'Browse Landing',
      component: 'Index',
      nodeStyle: 'start',
      description: 'Traveler discovers the marketplace via landing page',
    },
    {
      id: 'signup',
      route: '/signup',
      label: 'Sign Up',
      component: 'Signup',
      description: 'Create account with email or Google OAuth',
      tables: ['profiles', 'user_roles'],
    },
    {
      id: 'pending_approval',
      route: '/pending-approval',
      label: 'Await Approval',
      component: 'PendingApproval',
      nodeStyle: 'decision',
      tables: ['profiles'],
      branches: [
        { condition: 'Approved', targetStepId: 'search_listings', label: 'Approved' },
      ],
    },
    {
      id: 'search_listings',
      route: '/rentals',
      label: 'Search Listings',
      component: 'Rentals',
      description: 'Browse, filter, and search active listings',
      tables: ['listings', 'properties'],
      branches: [
        { condition: 'Found listing', targetStepId: 'view_property' },
        { condition: 'Post travel request', targetStepId: 'post_travel_request' },
      ],
    },
    {
      id: 'view_property',
      route: '/property/:id',
      label: 'View Property',
      component: 'PropertyDetail',
      description: 'View listing details, photos, amenities, pricing',
      tables: ['listings', 'properties'],
      branches: [
        { condition: 'Book now', targetStepId: 'checkout' },
        { condition: 'Place bid', targetStepId: 'place_bid' },
      ],
    },
    {
      id: 'place_bid',
      route: '/property/:id',
      label: 'Place Bid',
      component: 'BidFormDialog',
      description: 'Submit a bid offer on a biddable listing',
      tables: ['listing_bids', 'notifications'],
      branches: [
        { condition: 'Bid accepted', targetStepId: 'checkout', label: 'Accepted' },
        { condition: 'Counter-offer', targetStepId: 'place_bid', label: 'Counter', edgeStyle: 'dashed' },
        { condition: 'Rejected', targetStepId: 'search_listings', label: 'Rejected', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'post_travel_request',
      route: '/bidding',
      label: 'Post Travel Request',
      component: 'TravelRequestForm',
      description: 'Create a reverse-auction travel request for owners to bid on',
      tables: ['travel_requests'],
      branches: [
        { condition: 'Proposal received', targetStepId: 'review_proposals' },
      ],
    },
    {
      id: 'review_proposals',
      route: '/my-bids',
      label: 'Review Proposals',
      component: 'MyBidsDashboard',
      description: 'Review owner proposals on travel request',
      tables: ['travel_proposals'],
      branches: [
        { condition: 'Accept proposal', targetStepId: 'checkout' },
        { condition: 'Reject all', targetStepId: 'search_listings', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'checkout',
      route: '/checkout',
      label: 'Stripe Checkout',
      component: 'Checkout',
      nodeStyle: 'external',
      description: 'Secure payment via Stripe Checkout',
      edgeFunctions: ['create-booking-checkout'],
      tables: ['bookings'],
    },
    {
      id: 'booking_success',
      route: '/booking-success',
      label: 'Booking Confirmed',
      component: 'BookingSuccess',
      description: 'Payment confirmed, reservation details shown',
      edgeFunctions: ['verify-booking-payment'],
      tables: ['bookings', 'booking_confirmations'],
    },
    {
      id: 'checkin',
      route: '/checkin',
      label: 'Check In',
      component: 'TravelerCheckin',
      nodeStyle: 'decision',
      description: 'Confirm arrival or report issues at the property',
      tables: ['checkin_confirmations'],
      branches: [
        { condition: 'All good', targetStepId: 'stay_complete', label: 'Confirmed' },
        { condition: 'Issue reported', targetStepId: 'issue_resolution', label: 'Issue' },
      ],
    },
    {
      id: 'issue_resolution',
      route: '/admin',
      label: 'Issue Resolution',
      component: 'AdminCheckinIssues',
      roles: ['rav_admin'],
      description: 'RAV team resolves reported check-in issues',
      tables: ['checkin_confirmations'],
    },
    {
      id: 'stay_complete',
      route: '/',
      label: 'Stay Complete',
      component: 'Index',
      nodeStyle: 'end',
      description: 'Trip completed successfully, payout released to owner',
    },
  ],
};
