import type { FlowDefinition } from './types';

export const travelerLifecycle: FlowDefinition = {
  id: 'traveler-lifecycle',
  label: 'Renter Journey',
  description: 'End-to-end lifecycle from browsing to check-in. Renters can book directly, bid on listings, or post travel requests for owners to propose against.',
  primaryRole: 'renter',
  roleEmoji: '🧳',
  direction: 'TD',
  steps: [
    {
      id: 'browse',
      route: '/',
      label: 'Browse Landing',
      component: 'Index',
      nodeStyle: 'start',
      description: 'Renter discovers the marketplace via landing page',
    },
    {
      id: 'signup',
      route: '/signup',
      label: 'Sign Up',
      component: 'Signup',
      description: 'Create account with email or Google OAuth',
      tables: ['profiles', 'user_roles'],
    },
    {
      id: 'pending_approval',
      route: '/pending-approval',
      label: 'Await Approval',
      component: 'PendingApproval',
      nodeStyle: 'decision',
      tables: ['profiles'],
      branches: [
        { condition: 'Approved', targetStepId: 'search_listings', label: 'Approved' },
      ],
    },
    {
      id: 'explore_destinations',
      route: '/destinations',
      label: 'Explore Destinations',
      component: 'Destinations',
      description: 'Browse featured vacation destinations by region and state',
      branches: [
        { condition: 'Select destination', targetStepId: 'search_listings', label: 'Search in destination' },
      ],
    },
    {
      id: 'search_listings',
      route: '/rentals',
      label: 'Search Listings',
      component: 'Rentals',
      description: 'Browse, filter, and search active listings via text chat or voice search. Expired listings auto-filtered.',
      tables: ['listings', 'properties'],
      edgeFunctions: ['voice-search', 'text-chat'],
      branches: [
        { condition: 'Found listing', targetStepId: 'view_property', label: 'View listing' },
        { condition: 'Post travel request', targetStepId: 'post_travel_request', label: 'Request vacation' },
      ],
    },
    {
      id: 'view_property',
      route: '/property/:id',
      label: 'View Property',
      component: 'PropertyDetail',
      description: 'View listing details, photos, amenities, per-night pricing. Owner decides at listing time whether bidding is open.',
      tables: ['listings', 'properties'],
      branches: [
        { condition: 'Listing allows direct booking', targetStepId: 'checkout', label: 'Book directly' },
        { condition: 'Listing is open to bidding', targetStepId: 'place_bid', label: 'Place bid' },
        { condition: 'Propose different dates', targetStepId: 'place_bid', label: 'Date proposal', edgeStyle: 'dashed' },
        { condition: 'Request similar dates', targetStepId: 'post_travel_request', label: 'Inspired request', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'place_bid',
      route: '/property/:id',
      label: 'Place Bid',
      component: 'BidFormDialog',
      description: 'Submit a bid or date proposal on a listing. After submission, renter tracks the response on My Bids page.',
      tables: ['listing_bids', 'notifications'],
      branches: [
        { condition: 'Bid submitted', targetStepId: 'my_bids_dashboard', label: 'Track on My Bids' },
      ],
    },
    {
      id: 'post_travel_request',
      route: '/bidding',
      label: 'Post Travel Request',
      component: 'TravelRequestForm',
      description: 'Renter posts a reverse-auction request specifying destination, dates, budget — owners respond with proposals',
      tables: ['travel_requests'],
      branches: [
        { condition: 'Request posted', targetStepId: 'my_bids_dashboard', label: 'Track on My Bids' },
      ],
    },
    {
      id: 'my_bids_dashboard',
      route: '/my-bids',
      label: 'My Bids & Proposals',
      component: 'MyBidsDashboard',
      description: 'Renter tracks all listing bids and reviews owner proposals on travel requests. Counter-offers appear here for review and re-negotiation before accepting.',
      tables: ['listing_bids', 'travel_proposals'],
      branches: [
        { condition: 'Bid or proposal accepted', targetStepId: 'checkout', label: 'Pay now' },
        { condition: 'All rejected or expired', targetStepId: 'search_listings', label: 'Search again', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'checkout',
      route: '/checkout',
      label: 'Stripe Checkout',
      component: 'Checkout',
      nodeStyle: 'external',
      description: 'Secure payment via Stripe Checkout — full payment captured at booking',
      edgeFunctions: ['create-booking-checkout', 'stripe-webhook'],
      tables: ['bookings'],
    },
    {
      id: 'booking_success',
      route: '/booking-success',
      label: 'Booking Confirmed',
      component: 'BookingSuccess',
      description: 'Payment confirmed, reservation details shown, funds held in escrow',
      edgeFunctions: ['verify-booking-payment', 'stripe-webhook'],
      tables: ['bookings', 'booking_confirmations'],
      branches: [
        { condition: 'Renter cancels', targetStepId: 'renter_cancellation', label: 'Cancel booking', edgeStyle: 'dashed' },
        { condition: 'View bookings', targetStepId: 'my_bookings', label: 'My Bookings' },
      ],
    },
    {
      id: 'my_bookings',
      route: '/my-bookings',
      label: 'My Bookings',
      component: 'MyBookings',
      description: 'Renter views all bookings (upcoming, past, cancelled) with status tracking, cancellation, and issue reporting',
      tables: ['bookings', 'listings', 'properties', 'disputes'],
      branches: [
        { condition: 'Cancel booking', targetStepId: 'renter_cancellation', label: 'Cancel', edgeStyle: 'dashed' },
        { condition: 'Report issue', targetStepId: 'report_issue', label: 'Report issue', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'account_settings',
      route: '/account',
      label: 'Account Settings',
      component: 'AccountSettings',
      description: 'User manages profile (name, phone), password, data export, and GDPR account deletion (14-day grace period)',
      tables: ['profiles'],
      edgeFunctions: ['export-user-data', 'delete-user-account'],
      branches: [],
    },
    {
      id: 'report_issue',
      route: '/my-bookings',
      label: 'Report Issue',
      component: 'ReportIssueDialog',
      description: 'Renter reports a problem with a booking — submits dispute for admin review',
      tables: ['disputes'],
      branches: [],
    },
    {
      id: 'renter_cancellation',
      route: '/booking-success',
      label: 'Renter Cancellation',
      component: 'CancelBookingDialog',
      description: 'Renter-initiated cancellation with policy-based refund (flexible/moderate/strict/super_strict). Stripe refund processed automatically.',
      edgeFunctions: ['process-cancellation', 'send-cancellation-email'],
      tables: ['cancellation_requests', 'bookings'],
      nodeStyle: 'end',
    },
    {
      id: 'awaiting_owner_confirmation',
      route: '/booking-success',
      label: 'Awaiting Owner Confirmation',
      component: 'BookingSuccess',
      description: 'Owner has a configurable time window to confirm they can fulfill the booking. Extensions may be requested.',
      tables: ['booking_confirmations'],
      edgeFunctions: ['process-deadline-reminders'],
      branches: [
        { condition: 'Owner confirms', targetStepId: 'checkin', label: 'Confirmed' },
        { condition: 'Owner declines/times out', targetStepId: 'search_listings', label: 'Refunded', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'checkin',
      route: '/checkin',
      label: 'Check In',
      component: 'TravelerCheckin',
      nodeStyle: 'decision',
      description: 'Confirm arrival or report issues at the property',
      tables: ['checkin_confirmations'],
      branches: [
        { condition: 'All good', targetStepId: 'stay_complete', label: 'Confirmed' },
        { condition: 'Issue reported', targetStepId: 'issue_resolution', label: 'Issue' },
      ],
    },
    {
      id: 'contact_support',
      route: '/contact',
      label: 'Contact Support',
      component: 'Contact',
      description: 'Submit a support inquiry via contact form. Sends email notification to support team and confirmation to user.',
      edgeFunctions: ['send-contact-form'],
    },
    {
      id: 'issue_resolution',
      route: '/admin',
      label: 'Issue Resolution',
      component: 'AdminCheckinIssues',
      roles: ['rav_admin'],
      description: 'RAV team resolves reported check-in issues',
      tables: ['checkin_confirmations'],
    },
    {
      id: 'stay_complete',
      route: '/',
      label: 'Stay Complete',
      component: 'Index',
      nodeStyle: 'end',
      description: 'Trip completed successfully, payout released to owner',
    },
  ],
};
